sed -i 's/"checker.h"/"checker_bonus.h"/' checker_bonus.c
sed -i 's/"checker.h"/"checker_bonus.h"/' chk_init_bonus.c
sed -i 's/"checker.h"/"checker_bonus.h"/' chk_prin_bonus.c
sed -i 's/"checker.h"/"checker_bonus.h"/' chk_psoo_bonus.c
sed -i 's/"checker.h"/"checker_bonus.h"/' chk_read_bonus.c
sed -i 's/"checker.h"/"checker_bonus.h"/' chk_rota_bonus.c
sed -i 's/"checker.h"/"checker_bonus.h"/' chk_rrot_bonus.c
sed -i 's/"checker.h"/"checker_bonus.h"/' chk_swap_bonus.c
sed -i 's/"checker.h"/"checker_bonus.h"/' chk_trea_bonus.c
sed -i 's/"checker.h"/"checker_bonus.h"/' get_next_line_bonus.c
sed -i 's/"checker.h"/"checker_bonus.h"/' gnl_buff_analisis_bonus.c
sed -i 's/"checker.h"/"checker_bonus.h"/' gnl_buff_flush_bonus.c
sed -i 's/"checker.h"/"checker_bonus.h"/' gnl_join_bonus.c
sed -i 's/"checker.h"/"checker_bonus.h"/' gnl_my_free_bonus.c
sed -i 's/"checker.h"/"checker_bonus.h"/' gnl_read_to_buff_bonus.c
sed -i 's/"checker.h"/"checker_bonus.h"/' gnl_strlen_and_nl_bonus.c
sed -i 's/"checker.h"/"checker_bonus.h"/' gnl_strlen_bonus.c
sed -i 's/"checker.h"/"checker_bonus.h"/' gnl_substr_bonus.c
